name: CI

on:
  push:
    branches: [ master ]

jobs:
  main:
    runs-on: debian-latest
    steps:
      - uses: actions/checkout@v2
        run: |
          git push easonkamander.com:/var/www/citation/main.git master
