name: CI

on:
  push:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Main
        run: |
          git push easonkamander.com:/var/www/citation/main.git master
